# Site settings
title: Swati Jaiswal
email: jaiswalswati94atTheRategMail doT Com
description: > # this means to ignore newlines until "baseurl:"
  Keep Learning Keep Sharing.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://swati-jaiswal.github.io" # the base hostname & protocol for your site
twitter_username: swati12jaiswal
github_username:  curioswati

# Outputting
permalink: date

# Build settings
markdown: kramdown

#defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

#highlighting
highlighter: pygments
excerpt_separator: ""